version: '3.2'

services:
  database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
  # rmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=dev
  #     - RABBITMQ_DEFAULT_PASS=dev
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
